### PR TITLE
Add DMARC Reporting Docs

### PR DESCRIPTION
**Pull request by dragoangel**

### CODE REVIEW

**Comment by dragoangel** [comment]
Think also to add not about that option bcc is now broken or not?

**Comment by MAGICCC** [comment]
> 
> 
> Think also to add info or not about that option additional_address_bcc is now broken?

Yep you can use a textbox like
```
!!! bug
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
    nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
    massa, nec semper lorem quam in massa.
```

**Comment by andryyy** [comment]
Meh, I will need to check it, sorry. Enotime. :( Thanks for your great work. :)

**Comment by dragoangel** [comment]
@andryyy reminder :)

**Comment by FingerlessGlov3s** [comment]
Tested, and deployed.

Thank you for the leg work @dragoangel  :-)

**Comment by dragoangel** [comment]
Will resolve: https://github.com/mailcow/mailcow-dockerized/issues/3247

**Comment by SecretUsername** [comment]
Hi, what's up here? Great work @dragoangel, why doesn't it get merged?
@andryyy friendly reminder :)

**Comment by dragoangel** [comment]
@andryyy I updated docs to work with Rspamd 3.0 and fixed some spelling errors, can this be merged?

**Comment by FingerlessGlov3s** [comment]
@dragoangel, good job I follow this PR, didn't know I needed to update my config for rspamd3.0

**Comment by andryyy** [comment]
Thank you very much!

**Pull request merged**
