### PR TITLE
Small typo in nginx custom site information

### PR DESCRIPTION
**Pull request by ctrl-i**
Just missing a semi-colon.

### CODE REVIEW

**Comment by MAGICCC** [comment]
docs/u_e-update-hooks.md is already fine on master, no need for it in the PR

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Pull request closed without merging**
