### PR TITLE
Fix HOW TO sogo

### PR DESCRIPTION
**Pull request by MAGICCC**
It seems that you need to fully recreate SOGo **and** NGinx folder to see the new image

### CODE REVIEW

**Comment by mkuron** [comment]
That is not true. The svg file is only copied into the SOGo container. We don‘t even have a Dockerfile for nginx (we use the official image), so rebuilding the image will do nothing.

You may, however, need to reset the nginx container (`docker-compose rm -s nginx-mailcow; docker-compose up -d`) as nginx caches SOGo resources for a few hours.

**Comment by MAGICCC** [comment]
By rechecking it I just found out that my command is indeed wrong. I debugged this some hours in the first instance and used deprecated command. Care to unlock the PR so I can commit `docker-compose up -d --build sogo-mailcow`?

**Comment by mkuron** [comment]
Of course you need to rebuild Sogo, that‘s what the documentation says already. If you want to add something on clearing the Nginx cache (my command is not the only possible one for that and definitely not the fastest way to do it), go ahead.

**Comment by mkuron** [comment]
Your new commit has showed up now, but it is exactly equivalent to what the documentation previously said. You just combined the two commands into one. Please revert to what it originally said and only add something on clearing the Nginx cache.

**Comment by MAGICCC** [comment]
In my recent tests I only needed to invoke `docker-compose up -d --build sogo-mailcow` in order to 'update' the logo

**Comment by mkuron** [comment]
But that‘s what the commands previously in the documentation do too. So there is nothing that needs to be changed in the documentation?

**Comment by MAGICCC** [comment]
Ah welp, I have **literally no** idea what I did in the last hours, but somehow it didn't update the logo, but now it does...
Well either close the PR or merge it so users only need to invoke one command

**Pull request closed without merging**
