### PR TITLE
nginx

### PR DESCRIPTION
**Pull request by affenrakete**
- adding IPv6 to port 443
  * let's encrypt and all other are able to connect bei ipv6
- adding ssl tag
  * 'ssl on' can be omitted
- adding http2 tag
  * this tells Nginx to use HTTP/2 with supported browsers.

### CODE REVIEW

**Comment by affenrakete** [comment]
Without the first point let's encrypt will not be able to connect an verify the domain.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Pull request closed without merging**
