### PR TITLE
clarification about '/var/lib/docker' partition

### PR DESCRIPTION
**Pull request by JOduMonT**
#### because sometimes people try stuff.
while those configurations will interfere with how mailcow works it will be hard to see their impact through the mailcow logs

### CODE REVIEW

**Comment by MAGICCC** [comment]
It's nice to add such tiny things, but I am not sure if anyone actually uses it :)
I will think about it merging it, but you can fix some grammatical things

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Pull request closed without merging**
