### PR TITLE
Add Exchange Hybrid Setup

### PR DESCRIPTION
**Pull request by JUVOJustin**
Add Docs about how to use a mailcow as on premise mailserver in combination with office 365 / Exchange

### CODE REVIEW

**Comment by andryyy** [comment]
Hi Justin,

Thank you!

Perhaps we should add the MS servers as forwarding host and make clear that filtering now completely relies on MS (ieks, not recommended).

Inbound filtering mailcow side is broken so is neural learning etc. - we need to completely disable these components.

**Comment by JUVOJustin** [comment]
Hi @andryyy , 
you´re absolutely right. I added a step to add the forwading host and an notification box about the broken inbound filtering.

I didn´t found any documentation about forwardong hosts that i could link to. Is there any?

**Comment by andryyy** [comment]
There is none yet. :( But it is enough to point to /admin and "Forwarding hosts". :-)

**Comment by JUVOJustin** [comment]
Alright i added the path to the forwarding hosts menu. 

I think this documentation is in a "ready to be merged" state, isn´t it? :D

**Comment by andryyy** [comment]
Amazing!

Ready to merge for you?

**Comment by JUVOJustin** [comment]
Yup. Go for it 👍

**Comment by andryyy** [comment]
Very cool, thank you, again.

**Pull request merged**
