### PR TITLE
Nextcloud with OAuth2

### PR DESCRIPTION
**Pull request by mkuron**
As promised, here is the documentation on how to connect Nextcloud to Mailcow via OAuth2. Please don't merge yet, I'm hoping someone will test it first and report back if my instructions worked for them.

### CODE REVIEW

**Comment by mkuron** [comment]
Could you please show us the complete contents of the relevant tables (nc_users, nc_sociallogin_connect) and a screenshot of your social login OAuth settings page? I suspect that you have the identifier wrong somewhere.

**Comment by Miyamoto72** [comment]
social_login-screenshot
oauth-screenshot

```
MariaDB [nextcloud]> select * from oc_users;
+-------------------------+--------------------+----------------------------------------------------------------------------------------------------+-------------------------+
| uid                     | displayname        | password                                                                                           | uid_lower               |
+-------------------------+--------------------+----------------------------------------------------------------------------------------------------+-------------------------+
| Adminion                | NULL               | 2|$argon2i$v=19$m=65536,t=4,p=1$RlhXWDFrUGhteG5Qb3NJZQ$LpFEiq5LvZ3bf0TobksVf/vWIHNsPmEN+Vyu7t42Kn4 | adminion                |
| bela@example.com        | Béla Example       | 2|$argon2i$v=19$m=65536,t=4,p=1$dFZTVk9xSTlMWk5RY1FJUw$3YD1BC0bU816/7i/g6hC/DXPZIOljwxaGXXoRIlLmio | bela@example.com       |
| friedemann@example.com  | Friedemann Example | 2|$argon2i$v=19$m=65536,t=4,p=1$NFFYQ0V4VzBZYnR4RWNqbw$kuEK9sJKCtkAP2pnWsruHFsnTkj1uCWxXmUEOr6aG7I | friedemann@example.com |
| ove@example.com         | Ove Example        | 2|$argon2i$v=19$m=65536,t=4,p=1$WXlSOElPUHl2aVU5WHZnWg$C3/3IcA57l1aefnVAWawXPZ1NUXDmAg/xx2Hh6WF578 | ove@example.com        |
| thure@example.com       | Thure Example      | 2|$argon2i$v=19$m=65536,t=4,p=1$bnVLU3pORjVKS1Mzd01QRA$EhLRYI7F5PXaXgVnyaGNGCVKyh3er8/PS1/gYpx8y7c | thure@example.com      |
+-------------------------+--------------------+----------------------------------------------------------------------------------------------------+-------------------------+
MariaDB [nextcloud]> select * from oc_sociallogin_connect;
+--------------------+----------------------------+
| uid                | identifier                 |
+--------------------+----------------------------+
| Adminion           | Mailcow-Adminion           |
| ove@example.com    | Mailcow-ove@example.com    |
| thure@example.com  | Mailcow-thure@example      |
+--------------------+----------------------------+
3 rows in set (0.000 sec)
```
I modified the SQL commands given in the now merged docs to reflect the slightliy different names in my nextcloud database (prefix oc_ instead of _nc)

**Comment by mkuron** [comment]
That looks correct, though it‘s possible that Nextcloud expects the `@` to be encoded somehow. Could you please create a new user in Mailcow, use that to log into Nextcloud, and then check what entries are added to the database? Also, please post a screenshot of your other sociallogin settings (there are about ten checkboxes at the top).

**Comment by Miyamoto72** [comment]
Social login settings have been set like given in the Mailcow docs.
Upon logging in via Oauth I get a new line on oc_users:
`| Mailcow-testuser@example.com | Test User          | 2|$argon2i$v=19$m=65536,t=4,p=1$dTVYV056RGtLQkZYbW1GSg$LGIPGeAtqAJgFvTcwpUW/AcGn9C38x7pGPPmg3LBapg | mailcow-testuser@example.com |`

The other table, oc_sociallogin_connect, doesn't change at all.

**Comment by andryyy** [comment]
@mkuron just curious: is it possible to pull a storage quota from the oauth profile?

**Comment by mkuron** [comment]
Only by modifying the sociallogin plugin.

**Comment by andryyy** [comment]
Oh, okay. Thanks. :)

**Pull request merged**
