### PR TITLE
Nextcloud Update via CLI added

### PR DESCRIPTION
**Pull request by deepc2020**
Added command for a cli based Nextcloud update to documentation. Both ways, interactive and non-interactive for scripts and cron, are described.

### CODE REVIEW

**Comment by MAGICCC** [comment]
Thanks, but can you add an [admonition ](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)before the part of automatic updates to warn users that it may break?

**Comment by MAGICCC** [comment]
Will you implent the admonition @deepc2020?

**Comment by MAGICCC** [comment]
Will you implent the admonition @deepc2020?

**Review by DerLinkman — APPROVED** [review]

**Review by DerLinkman — APPROVED** [review]
Thanks!

**Pull request merged**
