### PR TITLE
Zeyple documentation

### PR DESCRIPTION
**Pull request by stevesbrain**
Use zeyple to auto encrypt communications. Possibly fixes https://github.com/mailcow/mailcow-dockerized/issues/797

### CODE REVIEW

**Comment by stevesbrain** [comment]
Is there anything further required of me to get this merged, or is this something you guys don't want? I can cancel the stale request if so. Cheers :blush:

**Comment by ntimo** [comment]
Hey,
I just found this and think it would be super super nice to have, why is this not being merged @andryyy? :)

**Comment by alexanderadam** [comment]
It looks like Zeyple was recently removed ([1](https://github.com/mailcow/mailcow-dockerized/commit/3136e020f6c0afed83feaddddbd05fff2029fc92), [2](https://github.com/mailcow/mailcow-dockerized/commit/abf33b75f44dff7b60c020ca8a350309786afc92)).

**Comment by andryyy** [comment]
No py3 and was not working well with mailcow. 

We can try to find another solution for this. :)

**Comment by alexanderadam** [comment]
@andryyy should we open a dedicated issue for this?

**Comment by andryyy** [comment]
You can open an issue but not expect me to work on it. Perhaps someone else wants to though.

**Comment by milkmaker** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Pull request closed without merging**
