### PR TITLE
Update Roundcube docs page going from 1.5 to 1.6

### PR DESCRIPTION
**Pull request by FingerlessGlov3s**
This is to update the docs page to install or upgrade to Roundcube 1.6.0 along with the needed 'sed' commands to make any necessary config changes going from 1.5 to 1.6

### CODE REVIEW

**Comment by MAGICCC** [comment]
Could you also edit the german variant of the file?

**Comment by FingerlessGlov3s** [comment]
Of course I can, can you or someone translate the comment bit? As I can't speak German and I fear google translate will do it wrong.

**Comment by MAGICCC** [comment]
Ah right

```diff
- # Type 'N' to "Do you want me to fix your local configuration" if prompted
+# Geben Sie 'N' ein, wenn folgender Dialog erscheint: "Do you want me to fix your local configuration".
````

```diff
- # If your going from 1.5 to 1.6 please run the config file changes below
+# Falls Sie von Version 1.5 auf 1.6 updaten, dann führen Sie folgende Befehle aus, um die Konfigurationsdatei anzupassen:`
```

**Comment by accolon** [comment]
When doing an upgrade, the `installto.sh` script shows `NOTICE: Update dependencies by running 'php composer.phar update --no-dev'`.

I always do this in the `/web/rc` folder afterwards which usually updates a few packages, especially after upgrading from 1.5 to 1.6.

Should this be added to the instructions?

**Comment by FingerlessGlov3s** [comment]
@accolon, I didn't get that notice or at least remember it, have you installed any extra plugins?

**Comment by accolon** [comment]
I'm only using the plugins mentioned in the docs, e.g. `carddav` or `password`.

Composer also updates dependencies which are part of Roundcube, like guzzle or bacon-qr-code, since the `composer.json` which is part of the "complete" RC tar.gz allows higher versions for those.

I didn't write down the changes it did this time, I will keep an eye on it. I just always updated the dependencies and was wondering if this should be added to the instructions.

**Comment by FingerlessGlov3s** [comment]
We could do the compose updates but then the dependencies wouldn't match the released complete version, which I'm not 100% sure we an want to do. I would think the ones released with Roundcube will be known good from the developers.

The official upgrade instructions only mention doing that if doing the upgrade manually. 🤔
https://github.com/roundcube/roundcubemail/blob/master/UPGRADING

**Comment by accolon** [comment]
Fine by me. You're right with regard to the upgrade instructions.

On the other hand, the `update.sh` script which is called by `installto.sh` seems to rebuild `composer.json` each time and it always prints out the notice about updating dependencies...

But since it has worked without this additional step for quite some time, it is probably best to keep it this way.

**Comment by accolon** [comment]
Oh, one additional thing:

They also renamed `smtp_server` to `smtp_host` in 1.6:
https://github.com/roundcube/roundcubemail/commit/893216cb297268d222ae49099e6654a304b72e3f

**Comment by FingerlessGlov3s** [comment]
Hehe the SED is correct but not the example config on first install, good spot.
I'll fix that

**Comment by MAGICCC** [comment]
thanks :)

**Pull request merged**
