### PR TITLE
Create third_party-autoarchiving

### PR DESCRIPTION
**Pull request by sschwetz**
Setup autoarchving with dovecot-archive

### CODE REVIEW

**Comment by andryyy** [comment]
Hi, thank you! I don't think we need the ofelia container. :)

**Comment by sschwetz** [comment]
I used the ofelia route as I already had the container running for other jobs and I prefer to keep the docker host’s crontab for the host. 

I will update the document with how to run it with a docker exec as well from corn

**Comment by andryyy** [comment]
We already have ofelia in the stack.

**Comment by sschwetz** [comment]
If that is the case should we also update https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-expunge/ ?

**Comment by andryyy** [comment]
Yes! Good catch. :)

**Comment by andryyy** [comment]
Thanks! Are you sure it's a cron compatible format? Iirc it also reads seconds. A `@every 4h` would be better imo.

I never checked that. I will merge and change it, ok?

**Comment by andryyy** [comment]
Can you check if the changes are fine for you?

**Comment by sschwetz** [comment]
I have updated a typo in the scheduler string, but it does need to have seconds declared

**Comment by sschwetz** [comment]
@andryyy can you advise if you are happy with this now?

**Pull request closed without merging**
