### PR TITLE
Remove infinite redirect

### PR DESCRIPTION
**Pull request by john-montgomery2003**
Was having issues with infinite redirects, commenting out 
RewriteRule ^/?(.*) https://%{HTTP_HOST}/$1 [R=301,L]
[line61] seemed to fix the issue, and continues to redirect the http to https

### CODE REVIEW

**Comment by andryyy** [comment]
Hm, the config works fine on multiple installations, Are you sure it's a problem with the RP config we provide?

It might introduce other problems when we merge this.

**Comment by john-montgomery2003** [comment]
Cant be sure its this specific config, could be because of my other configs - I'll see if it persists on a fresh install, but i'll close for now.

**Comment by andryyy** [comment]
Can you report back? Really curious. :) It might be important.

**Comment by john-montgomery2003** [comment]
my bad - seems like there was some other issue, which i cant seem to isolate at the moment, it doesn't seem to be the fault of that line, but somehow commenting it fixed the issue I was facing :/ apologies for the wasted time

**Pull request closed without merging**
