### PR TITLE
Third-party: Borgmatic Backup

### PR DESCRIPTION
**Pull request by kaechele**
This guide describes setting up automatic recurring backups using
borgmatic.
This is a good alternative to juggling tar archives.

Signed-off-by: Felix Kaechele <felix@kaechele.ca>

### CODE REVIEW

**Comment by andryyy** [comment]
Thank you very much for this! :) I try to check it tomorrrow and report back.

**Comment by kaechele** [comment]
FYI: I have actually tested this guide on a clean mailcow install (both backup and restore) and it worked for me.
So I hope this is useful for people.

I run it on my instance pretty much in this configuration and with the large amount of snapshots available I can always so go back in time without messing up things too much.
Due to the fact that borg allows you to mount archives as if they were file systems you can even pull out an individual message from the maildir if necessary. It's pretty neat.

Happy to take any feedback both on workability of this guide as well as writing style, spelling and grammar.

**Comment by andryyy** [comment]
Sorry, I was so busy, I almost forgot it.

**Thank you!** :)

**Comment by omexlu** [comment]
I use borg to backup my whole servers so I don't need a third party option, but I find that It will be a good idea to include this as standard into mailcow with more configuration options over the mailcow gui :)

Maybe a feature for feature :)

**Pull request merged**
