### PR TITLE
SOGo Integrator now built into Connector

### PR DESCRIPTION
**Pull request by mkuron**
Also, don't install any other add-ons by default.

Fixes #171. Fixes #172.

### CODE REVIEW

**Comment by andryyy** [comment]
Cool, thanks. Feel free to merge when you think it's complete.

**Comment by mkuron** [comment]
@dragoangel, please check whether this works for you too.

**Comment by andryyy** [comment]
Thanks :)

**Comment by Braintelligence** [comment]
@mkuron Hey, can you confirm if it's possible to run multiple SOGo connectors? Or can I only have one domain active in that way per Thunderbird instance?

**Comment by mkuron** [comment]
You can obviously only install the plugin once. It automatically configures itself based on the default IMAP account and has no way to manually configure.

If you want to use multiple users' calendars/address books, the best solution is to set up ACLs to share them with your primary user.

**Comment by Braintelligence** [comment]
What if I have a mailcow running many multiple domains and I want to use multiple mail accounts separately together with their respective calendars and address books without sharing them between those accounts?

I guess I'll have to set them up the old way as remote address books and calendars, by inputting the Card/CalDAV-URL right?

**Comment by mkuron** [comment]
Correct. That's just a limitation of the plugin. I tend to use sharing for this situation though, which you can even use between multiple domains.

**Comment by Braintelligence** [comment]
I understand. Thank you very much for clarifying. Maybe we should put this bit into the docs for those that touched the integrator functionality for the first time, like me. I only worked with the Connector before.

**Pull request merged**
