### PR TITLE
Roundcube admin login

### PR DESCRIPTION
**Pull request by balping**
Same as https://github.com/mailcow/mailcow-dockerized/pull/3849

### CODE REVIEW

**Comment by andryyy** [comment]
Thank you!! :) Give me some time to check it, please.

**Comment by DerLinkman** [comment]
Hi, is it still working?
Can you test it again, before we merge it?

**Comment by balping** [comment]
Hi @DerLinkman 

It wasn't accurate, but I updated it and it is now compatible with the latest mailcow version.

**Comment by balping** [comment]
I've no idea why there is a merge conflict, but to me it looks it's safe to merge

**Review by DerLinkman — COMMENTED** [review]
With these changes it looks fine now :)

**Pull request merged**
