### PR TITLE
add instruction for outlook 2016

### PR DESCRIPTION
**Pull request by mritzmann**
The new Outlook 2016 Setup Assistent for EAS didn't work with Mailcow. See this Issue with explanations from @mkuron: https://github.com/mailcow/mailcow-dockerized/issues/615#issuecomment-332317644

This PR add instruction for Outlook 2016 to the docs.

### CODE REVIEW

**Comment by andryyy** [comment]
This seems to only affect Outlook from Office 365 packages. Can you mention this in your PR? :-)

**Comment by mritzmann** [comment]
Agreed. I corrected it. :-)

**Comment by Tschlienger** [comment]
My friend and I just set up a new mailcow server and everything works just fine. We discovered that we had to enable TLS 1.0 for Outlook to be able to use autodiscover. Even then, only the old setup (as you mentioned in your PR very nicely, thanks for that btw), the new setup agent still doesn't work on March 12th. Are there any updates about why this is happening? Or did anyone find a solution for that yet? We will have some very basic experienced users who will be clearly overwhelmed if we tell them to use the old setup.

Thanks,
Tobias

**Comment by mritzmann** [comment]
@Tschlienger See also: https://github.com/mailcow/mailcow-dockerized/issues/615#issuecomment-332317644

**Pull request merged**
