### PR TITLE
Add dovecot missing ssl files as common problem

### PR DESCRIPTION
**Pull request by balping**
See https://github.com/mailcow/mailcow-dockerized/issues/2672

### CODE REVIEW

**Comment by andryyy** [comment]
These file are there by default. It is actually not a common problem. :)

Furthermore your file permissions are different from the original files. That may confuse people. 

After bootstrapping acme-mailcow one can have even more files and folders there. 

I think that's not a common problem and people should follow and understand the docs when exchanging the certificates.

**Comment by balping** [comment]
> These file are there by default. It is actually not a common problem. :)

Well, I ran into the same issue twice while installing mailcow on two servers, separated roughly by a year and I just thought I would spare myself next time (and others) from this hour of painful debugging. (It *is* painful as the container restarts every couple of seconds and therefore you can't really read any logs.)  But I can see  `generate_config.sh` should copy  `dhparams.pem` from  `data/assets/ssl-example` to `data/assets/ssl`, so I don't know what I did wrong, maybe I deleted it accidentally. There's also a number of people who encountered it in the thread linked above.

> Furthermore your file permissions are different from the original files. That may confuse people.

I don't mind changing the permissions to the default ones, I just copied the output of `ll`

> After bootstrapping acme-mailcow one can have even more files and folders there.

True, maybe I should add something along the lines *"when using custom certificates"*

**Comment by balping** [comment]
@andryyy I incorporated some of your notes. If you think this is unnecessary, feel free to close it.

**Comment by Blackclaws** [comment]
This issue is common if you don't run generate-config but instead copy an existing mailcow.conf over from a different location and customize it manually. I just ran into this as well because I had to recheckout the data folder but I already had the config.

**Pull request merged**
