### PR TITLE
Add SOGo HOW TO for changing theme and logo

### PR DESCRIPTION
**Pull request by MAGICCC**
Thought of adding this while I read https://github.com/mailcow/mailcow-dockerized/issues/1111

### CODE REVIEW

**Comment by Braintelligence** [comment]
Hey guys, how come I don't see these changes in https://mailcow.github.io/mailcow-dockerized-docs/ yet? ☹️

**Comment by MAGICCC** [comment]
The travis build failed and @andryyy wasn't that active enough to rebuild it :)

**Comment by Braintelligence** [comment]
Ah I see, thanks :D

**Comment by mkuron** [comment]
No, the build after the merge has succeeded. I think the reason why it isn‘t showing up is that @MAGICCC forgot to add the new page to the table of contents, so it doesn‘t get built.

**Pull request merged**
